# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6537559015e20775fd5337c07f2db3a34c34108a9b380602222082ae93336c0b7310d2b9633c45cff8441b364c2f8239437d7b88957b795abf9f7bde4afaca8

test:
  secret_key_base: cf05f4607e69dee0688639c510fe8f829256810c5c7e4125a5b39aae416aa370c5e78bab1d04873ebe74d086a304d260a3de4443c52148e694695a1ac61a7aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
